
GET http://localhost:3000


###
POST http://localhost:3000/assets
Content-Type: application/json

{
  "id": "123",
  "symbol": "BTC"
}

###
GET http://localhost:3000/assets



###
POST http://localhost:3000/orders
Content-Type: application/json

{
  "assetId": "123",
  "price": 188.98

}

###
GET http://localhost:3000/orders



