version: '3.1'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app

  db:
    build: ./mongo_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: db
      MONGODB_DATABASE: nest

